#!/usr/bin/env bash

if [ $#  -ne 2 ]; then
    echo "Usage: <commit message>"
    exit 1
fi

git add .; git commit -m '$1'; git push;
echo "Successfully added, commited and pushed changes to Github"
